name: "nightly"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  spec:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - '2.7'
          - '3.2'
        include:
          - ruby_version: '2.7'
            puppet_version: '~> 7.0'
          - ruby_version: '3.2'
            puppet_version: '~> 8.0'
    name: "spec (ruby ${{ matrix.ruby_version }} | puppet ${{ matrix.puppet_version }})"
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_ci.yml@main"
    secrets: "inherit"
    with:
      ruby_version: ${{ matrix.ruby_version }}
      puppet_gem_version: ${{ matrix.puppet_version }}

  acceptance:
    needs: spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    secrets: "inherit"
    with:
      flags: '--custom-matrix ./.github/matrix.json'
